### ISSUE TITLE
mobile client - Screen fragments should never be restored

### ISSUE THREAD

**Issue by mlsmaycon** [netbirdio/netbird#1004]
**Describe the problem**
Crash issue with NetBird 0.0.13

**Additional context**
Stack trace:
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.netbird.client/io.netbird.client.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3909)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4055)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8401)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:631)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:362)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
	at io.netbird.client.MainActivity.onCreate(MainActivity.java:46)
	at android.app.Activity.performCreate(Activity.java:8538)
	at android.app.Activity.performCreate(Activity.java:8502)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1440)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3890)
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
	... 27 more
Caused by: java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.
	at com.swmansion.rnscreens.ScreenFragment.<init>(ScreenFragment.kt:54)
	... 30 more
```

**Comment by mlsmaycon** [comment]
fixed in 0.0.14
