### ISSUE TITLE
Netbird - No Identity Providers work ! Keycloak - Login Error: User state: Unauthenticated

### ISSUE THREAD

**Issue by luckylinux** [netbirdio/netbird#1715]
**Describe the problem**
 After trying to get Netbird Self Hosted with Authentik and getting weird errors (https://github.com/netbirdio/netbird/issues/1684) and no help so far, I decided to give a try to:
- Netbird + Zitadel -> This apparently causes some issues (Zitadel related i/o timeout for connection between PostgreSQL and Zitadel-Server, probably cause is 100% CPU usage on my VPS Server and extremely high memory/RAM usage in Zitadel)
- Netbird + Keycloak -> This results in a "Login Error: User state: Unauthenticated". 

Nothing can be extracted from the logs of `keycloak` nor `netbird-management` Docker Container.

Looking at https://github.com/netbirdio/netbird/issues/1590, I am also running into the "CORS Missing Allow Origin".

**To Reproduce**

1. Setup Keycloak and Netbird according to the current version of https://docs.netbird.io/selfhosted/identity-providers#keycloak, both running behind Traefik Reverse Proxy with Letsencrypt provided TLS Certificates.
2. Visit https://netbird.MYDOMAIN.TLD
3. Get `Login Error: User state: Unauthenticated`

**Expected behavior**

Netbird working correctly.

**Are you using NetBird Cloud?**

Netbird self-hosted.

**NetBird version**

`netbird version`

**NetBird status -d output:**

Not sure how to do this:
- `netbird-management` container: `netbird: command not found`
- `netbird-dashboard` container: `netbird: command not found`
- `netbird-signal` container: `Error: crun: executable file `/bin/sh` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found`
- `netbird-coturn` container: `netbird: command not found`

**Screenshots**

**Additional context**

Environment same as in https://github.com/netbirdio/netbird/issues/1684 (Podman 4.9.3).

**Comment by mlsmaycon** [comment]
hello @luckylinux can you share logs from the following containers:

dashboard:
```shell
docker compose logs dashboard
```
management
```shell
docker compose logs management
```

Can you also share the content of your setup.env? you can mask your domain names, and client IDs, just make sure your are using the same masking value for the same real values.

**Comment by luckylinux** [comment]
Sure @mlsmaycon 

I had to adjust a bit the command though since I am using Podman and not Docker ...

`podman logs netbird-dashboard`
[podman_logs_netbird-dashboard.log](https://github.com/netbirdio/netbird/files/14628452/podman_logs_netbird-dashboard.log)



`podman logs netbird-management`

[podman_logs_netbird-management.log](https://github.com/netbirdio/netbird/files/14628453/podman_logs_netbird-management.log)

`setup.env`
[setup.env.txt](https://github.com/netbirdio/netbird/files/14628459/setup.env.txt)

**Comment by Zaryu** [comment]
Are there any news on this? Also unauthenticated running via keycloak. 
Also getting the same CORS error as above. all set up like in the documentation mentioned above.

`
content.js:364 getEmbedInfo
content.js:425 OEMBED https://netbird.MYDOMAIN.tld/?state=EmabodHrAU&session_state=bf19a860-aa59-40d2-847a-6e70c172b05b&iss=https%3A%2F%2Fauth.MYDOMAIN.tld%2Frealms%2FMYREALM&code=fe9d32ef-9d35-4c23-8350-598ac78cf784.bf19a860-aa59-40d2-847a-6e70c172b05b.b7a2ec9a-1fc9-4850-a12c-d5ee66d01aff#callback
2731-e746de7d02695f25.js:1 Checking to see if there is an authorization response to be delivered.
2731-e746de7d02695f25.js:1 Potential authorization request  https://netbird.MYDOMAIN.tld/ Object EmabodHrAU fe9d32ef-9d35-4c23-8350-598ac78cf784.bf19a860-aa59-40d2-847a-6e70c172b05b.b7a2ec9a-1fc9-4850-a12c-d5ee66d01aff undefined
2731-e746de7d02695f25.js:1 Delivering authorization response
/?state=EmabodHrAU&session_state=bf19a860-aa59-40d2-847a-6e70c172b05b&iss=https%3A%2F%2Fauth.MYDOMAIN.tld%2Frealms%2FMYREALM&code=fe9d32ef-9d35-4c23-8350-598ac78cf784.bf19a860-aa59-40d2-847a-6e70c172b05b.b7a2ec9a-1fc9-4850-a12c-d5ee66d01aff#callback:1 Access to fetch at 'https://auth.MYDOMAIN.tld/realms/MYREALM/protocol/openid-connect/token' from origin 'https://netbird.MYDOMAIN.tld' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
auth.MYDOMAIN.tld/realms/MYREALM/protocol/openid-connect/token:1 
        
        
       Failed to load resource: net::ERR_FAILED
2731-e746de7d02695f25.js:1 
        
        
       
        
       Uncaught (in promise) TypeError: Failed to fetch
    at FetchRequestor.xhr (2731-e746de7d02695f25.js:1:82495)
    at BaseTokenRequestHandler.performTokenRequest (2731-e746de7d02695f25.js:1:79114)
    at AuthorizationNotifier.listener (2731-e746de7d02695f25.js:1:56541)
    at AuthorizationNotifier.onAuthorizationComplete (2731-e746de7d02695f25.js:1:65206)
    at 2731-e746de7d02695f25.js:1:66271
`

**Comment by Zaryu** [comment]
> Are there any news on this? Also unauthenticated running via keycloak. Also getting the same CORS error as above. All set up like in the documentation mentioned above.
> 
> ```
>        content.js:364 getEmbedInfo
>        content.js:425 OEMBED https://netbird.MYDOMAIN.tld/?state=EmabodHrAU&session_state=bf19a860-aa59-40d2-847a-6e70c172b05b&iss=https%3A%2F%2Fauth.MYDOMAIN.tld%2Frealms%2FMYREALM&code=fe9d32ef-9d35-4c23-8350-598ac78cf784.bf19a860-aa59-40d2-847a-6e70c172b05b.b7a2ec9a-1fc9-4850-a12c-d5ee66d01aff#callback
>        2731-e746de7d02695f25.js:1 Checking to see if there is an authorization response to be delivered.
>        2731-e746de7d02695f25.js:1 Potential authorization request  https://netbird.MYDOMAIN.tld/ Object EmabodHrAU fe9d32ef-9d35-4c23-8350-598ac78cf784.bf19a860-aa59-40d2-847a-6e70c172b05b.b7a2ec9a-1fc9-4850-a12c-d5ee66d01aff undefined
>        2731-e746de7d02695f25.js:1 Delivering authorization response
>        /?state=EmabodHrAU&session_state=bf19a860-aa59-40d2-847a-6e70c172b05b&iss=https%3A%2F%2Fauth.MYDOMAIN.tld%2Frealms%2FMYREALM&code=fe9d32ef-9d35-4c23-8350-598ac78cf784.bf19a860-aa59-40d2-847a-6e70c172b05b.b7a2ec9a-1fc9-4850-a12c-d5ee66d01aff#callback:1 Access to fetch at 'https://auth.MYDOMAIN.tld/realms/MYREALM/protocol/openid-connect/token' from origin 'https://netbird.MYDOMAIN.tld' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
>        auth.MYDOMAIN.tld/realms/MYREALM/protocol/openid-connect/token:1 
> 
>  
>        Failed to load resource: net::ERR_FAILED
> 
> 
>        2731-e746de7d02695f25.js:1 
>   
>         
>        
>        Uncaught (in promise) TypeError: Failed to fetch
>     at FetchRequestor.xhr (2731-e746de7d02695f25.js:1:82495)
>     at BaseTokenRequestHandler.performTokenRequest (2731-e746de7d02695f25.js:1:79114)
>     at AuthorizationNotifier.listener (2731-e746de7d02695f25.js:1:56541)
>     at AuthorizationNotifier.onAuthorizationComplete (2731-e746de7d02695f25.js:1:65206)
>     at 2731-e746de7d02695f25.js:1:66271
> ```

My problem is solved. The issue was that the user somehow hasn't had the default-roles-apps role, and with that no uma_authorization and no offline_access roles. Put the role back an it works.

**Comment by luckylinux** [comment]
@mlsmaycon : any News on this ? It's really unfortunate I'm not getting anything working.

At least the Webpage should show something useful IMHO, not just crash the entire thing (and the Logs don't really tell much).

**Comment by luckylinux** [comment]
I just noticed there might be something related to Traefik Reverse Proxy going on ...

At the moment I only had the Dashboard reverse Proxy, but trying a Netbird Installation from Scratch using `./configure.sh` I get these Warnings:
```
The following forwards have to be setup:
- https://netbird.MYDOMAIN.TLD:443 -http-> dashboard:80
- https://netbird.MYDOMAIN.TLD:443/api -http-> management:443
- https://netbird.MYDOMAIN.TLD:443/management.ManagementService/ -grpc-> management:443
- https://netbird.MYDOMAIN.TLD:443/signalexchange.SignalExchange/ -grpc-> signal:80
You most likely also have to change NETBIRD_MGMT_API_ENDPOINT in base.setup.env and port-mappings in docker-compose.yml.tmpl and rerun this script.
 The target of the forwards depends on your setup. Beware of the gRPC protocol instead of http for management and signal!
You are also free to remove any occurrences of the Letsencrypt-volume netbird-letsencrypt

```

So actually I am missing the 2nd, 3rd and 4th Rule ...

**Comment by nazarewk** [comment]
Hello @luckylinux,

We're currently reviewing our open issues and would like to verify if this problem still exists in the [latest NetBird version](https://github.com/netbirdio/netbird/releases).

Could you please confirm if the issue is still there?

We may close this issue temporarily if we don't hear back from you within **2 weeks**, but feel free to reopen it with updated information.

Thanks for your contribution to improving the project!

**Comment by luckylinux** [comment]
@nazarewk Not sure I'll have Time in the next 2 Weeks to troubleshoot this 😥.

I had to switch to "pure" Wireguard since I was stuck on getting this to work in 2024 ...

**Comment by jonathanschlitt** [comment]
The Problem still exists for me with Traefik, Keycloak and Netbird in the latent version. I also commented it with my work acount on another open issue.

https://github.com/netbirdio/netbird/issues/2442#issuecomment-3200070065

**Comment by jacobjonz** [comment]
The problem exists even today. Had the exact same behavior.

**Comment by n-sc** [comment]
Push. Same problem with Keycloak :(

EDIT: I got it up and running, see [my comment](https://github.com/netbirdio/netbird/issues/2442#issuecomment-3723478782) in #2442.

**Comment by bashnotscript** [comment]
I finally got this working on my side, sharing what fixed it in case it helps someone else.

In my setup I was automating NetBird + Keycloak with Ansible, and the issue was not just one bad setting. It was a mix of HTTPS, URL consistency, startup timing, and trust of self-signed certs.

What made the difference for me:

- I had to enable HTTPS for both Keycloak and the NetBird nginx endpoint. In my lab I used self-signed certs for testing.
- The issuer/public realm URLs had to be completely consistent. I used the same `https://<host>/realms/netbird` value so discovery and token validation matched properly.
- For automation, I stopped calling Keycloak admin endpoints through the public/proxied URL and used the local admin API instead (`http://127.0.0.1:8080`)
- Because I was using self-signed HTTPS on Keycloak, I also had to make `netbird-management` trust that cert for backend OIDC communication by mounting the cert and setting `SSL_CERT_FILE`.

These are the sanitized env values I ended up using:

```
NETBIRD_PUBLIC_URL=<redacted>
NETBIRD_OIDC_CLIENT_ID=netbird-client
NETBIRD_OIDC_CLIENT_SECRET=<redacted>
NETBIRD_OIDC_ISSUER=https://<redacted>/realms/netbird
NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT=https://<redacted>/realms/netbird/.well-known/openid-configuration
NETBIRD_USE_AUTH0=false
NETBIRD_AUTH_CLIENT_ID=netbird-client
NETBIRD_AUTH_SUPPORTED_SCOPES=openid profile email offline_access api
NETBIRD_AUTH_AUDIENCE=netbird-client
NETBIRD_AUTH_DEVICE_AUTH_CLIENT_ID=netbird-client
NETBIRD_AUTH_DEVICE_AUTH_AUDIENCE=netbird-client
NETBIRD_MGMT_IDP=keycloak
NETBIRD_IDP_MGMT_CLIENT_ID=netbird-backend
NETBIRD_IDP_MGMT_CLIENT_SECRET=<redacted>
NETBIRD_IDP_MGMT_EXTRA_ADMIN_ENDPOINT=https://<redacted>/admin/realms/netbird
NETBIRD_STORE_ENGINE_POSTGRES_DSN=postgres://<redacted>
```

For me, the main causes were:

1. browser login flow needed HTTPS
2. issuer/discovery URLs had to match exactly
3. admin automation should not go through a redirecting proxy URL
4. self-signed Keycloak cert had to be trusted by NetBird management
5. service readiness/order mattered more than I expected

Hopefully this saves someone else some time.

**Comment by PizzaLovingNerd** [comment]
Hello, we are closing this as stale, as this is for an old NetBird setup.

#2442 seems to be tracking this issue as well, and @bashnotscript may have a solution for anyone running into this issue again.

Cheers!

**Comment by luckylinux** [comment]
Well somehow I managed to get it working with Authentik on a new Installation.

I cannot remember what the exact Issue was.

Maybe simply selecting a suitable Signing Key (either RSA or ECDSA self-signed) made the Trick, or possibly it was something else entirely.
