### ISSUE TITLE
Blank page instead of webui on self hosted via traefik

### ISSUE THREAD

**Issue by demanuPL** [netbirdio/netbird#1920]
I'm getting blank page instead of any webui or even zitadel login page. I don't have any errors in docker logs, traefik shows correct endpoints setup. 

only logs I'm getting are from browser:

`2472-d2675ce40f6cc81a.js:1 SyntaxError: Expected ',' or '}' after property value in JSON at position 158 (line 1 column 159)
    at JSON.parse (<anonymous>)
    at 17258 (page-e422bc205eb5d866.js:1:8231)
    at __webpack_require__ (webpack-3f95d46cb44e434a.js:1:185)
    at loadConfig (page-e422bc205eb5d866.js:1:6012)
    at 82142 (page-e422bc205eb5d866.js:1:5419)
    at __webpack_require__ (webpack-3f95d46cb44e434a.js:1:185)
    at 5721 (page-e422bc205eb5d866.js:1:248)
    at __webpack_require__ (webpack-3f95d46cb44e434a.js:1:185)
    at N (2472-d2675ce40f6cc81a.js:9:2154)
    at S (2472-d2675ce40f6cc81a.js:9:1433)

window.console.error @ 2472-d2675ce40f6cc81a.js:1
fd9d1056-94d51a7229cdc644.js:9 Uncaught SyntaxError: Expected ',' or '}' after property value in JSON at position 158 (line 1 column 159)
    at JSON.parse (<anonymous>)
    at 17258 (page-e422bc205eb5d866.js:1:8231)
    at __webpack_require__ (webpack-3f95d46cb44e434a.js:1:185)
    at loadConfig (page-e422bc205eb5d866.js:1:6012)
    at 82142 (page-e422bc205eb5d866.js:1:5419)
    at __webpack_require__ (webpack-3f95d46cb44e434a.js:1:185)
    at 5721 (page-e422bc205eb5d866.js:1:248)
    at __webpack_require__ (webpack-3f95d46cb44e434a.js:1:185)
    at N (2472-d2675ce40f6cc81a.js:9:2154)
    at S (2472-d2675ce40f6cc81a.js:9:1433)

netbird.xxx.xxx/:1 Uncaught (in promise) SyntaxError: Expected ',' or '}' after property value in JSON at position 158 (line 1 column 159)
    at JSON.parse (<anonymous>)
    at 17258 (page-e422bc205eb5d866.js:1:8231)
    at __webpack_require__ (webpack-3f95d46cb44e434a.js:1:185)
    at loadConfig (page-e422bc205eb5d866.js:1:6012)
    at 82142 (page-e422bc205eb5d866.js:1:5419)
    at __webpack_require__ (webpack-3f95d46cb44e434a.js:1:185)
    at 5721 (page-e422bc205eb5d866.js:1:248)
    at Function.__webpack_require__ (webpack-3f95d46cb44e434a.js:1:185)

netbird.xxx.xxx/:1 Uncaught (in promise) SyntaxError: Expected ',' or '}' after property value in JSON at position 158 (line 1 column 159)
    at JSON.parse (<anonymous>)
    at 17258 (layout-4138352c86c07010.js:1:28337)
    at __webpack_require__ (webpack-3f95d46cb44e434a.js:1:185)
    at loadConfig (page-e422bc205eb5d866.js:1:6012)
    at 82142 (layout-4138352c86c07010.js:1:18716)
    at __webpack_require__ (webpack-3f95d46cb44e434a.js:1:185)
    at 33838 (layout-4138352c86c07010.js:1:19413)
    at Function.__webpack_require__ (webpack-3f95d46cb44e434a.js:1:185)

netbird.xxx.xxx/:1 The resource https://netbird.xxx.xxx/_next/static/media/7385e8d9d3c5518f-s.p.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

netbird.xxx.xxx/:1 The resource https://netbird.xxx.xxx/_next/static/css/1e61baa058975865.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

netbird.xxx.xxx/:1 The resource https://netbird.xxx.xxx/_next/static/media/7385e8d9d3c5518f-s.p.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

netbird.xxx.xxx/:1 The resource https://netbird.xxx.xxx/_next/static/css/1e61baa058975865.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`

**Comment by jamez01** [comment]
Getting same exact error.

**Comment by OTheNonE** [comment]
Having this issue too
