### ISSUE TITLE
The advanced Settings are displayed to enable you to enter the private server address

### ISSUE THREAD

**Issue by Frankzhang854** [netbirdio/netbird#2787]
The latest version of 0.30.3 can not pop up the advanced Settings interface on Windows11 and Windows10, but version 0.28.1 can, please ask what Settings are modified in the latest version? If so, what does the latest version do to pop up advanced Settings to fill in the private server address?
![图片_20241026091315](https://github.com/user-attachments/assets/71b03952-3346-45f2-ab34-2271faf09d5a)

**Comment by soundslike82** [comment]
I have exactly the saome problem. My mac and another laptop are working but only my X1 nano isn't. I've sent an email to coustomer center but I have't got any answer.

**Comment by liuyishengaaa** [comment]
you can use this command   "netbird up --management-url <https://netbird.example.com:33073> --setup-key xxx"

xxx = your setup-key

**Comment by Frankzhang854** [comment]
This command can be installed, but it is not possible to visually modify the server address to connect to the custom server as before, so it is difficult for people who do not understand the code.

**Comment by Frankzhang854** [comment]
This command can be installed, but it is not possible to visually modify the server address to connect to the custom server as before, so it is difficult for people who do not understand the code.

**Comment by mlsmaycon** [comment]
I've tested it on Windows 11 on an RDP connection with the 0.31.0 version, and it seems to be working fine. 

Can you upgrade your client and test again?

**Comment by RoyLi-Pvt** [comment]
ver 0.34.1 still can't open gui

**Comment by silencer404** [comment]
> I've tested it on Windows 11 on an RDP connection with the 0.31.0 version, and it seems to be working fine.
> 
> Can you upgrade your client and test again?

same issue on 0.35.2 ，windows10 
How can i debug netbird_ui.exe just like :

```
netbird service stop
.\PsExec64.exe -s cmd.exe /c "netbird up -F --log-level debug > c:\windows\temp\netbird.out.log 2>&1"
```

**Comment by lixmal** [comment]
Could you please test the `netbird-ui` from this archive https://github.com/netbirdio/netbird/actions/runs/12653674714/artifacts/2396199859

I wasn't able to reproduce the issue with the `zh-CN` locale.

**Comment by silencer404** [comment]
> Could you please test the `netbird-ui` from this archive https://github.com/netbirdio/netbird/actions/runs/12653674714/artifacts/2396199859
> 
> I wasn't able to reproduce the issue with the `zh-CN` locale.

It seems not work on my pc.
Here is logs:
```
2025-01-08T01:22:47+08:00 INFO client/ui/client_ui.go:684: command settings executed: 2025/01/08 01:22:47 Fyne error:  font load error
2025/01/08 01:22:47   Cause: collections not allowed
2025/01/08 01:22:47   At: /home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/internal/painter/font.go:197
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff690ded864]

goroutine 1 [running, locked to thread]:
fyne.io/fyne/v2/internal/painter.(*dynamicFontMap).ResolveFace(0xc000734630, 0x20)
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/internal/painter/font.go:362 +0x64
fyne.io/fyne/v2/internal/painter.walkString({0x7ff691f33e80, 0xc000734630}, {0xc0002de93c?, 0x0?}, 0x380, {0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/internal/painter/font.go:256 +0xba
fyne.io/fyne/v2/internal/painter.MeasureString({0x7ff691f33e80?, 0xc000734630?}, {0xc0002de93c?, 0x0?}, 0x0?, {0x0, 0x0, 0x0, 0x0, 0x0, ...})
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/internal/painter/font.go:207 +0x6f
fyne.io/fyne/v2/internal/painter.measureText({0xc0002de93c, 0x0}, 0x41600000, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, {0x0, ...})
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/internal/painter/font.go:233 +0xb1
fyne.io/fyne/v2/internal/painter.RenderedTextSize({0xc0002de93c, 0x0}, 0x41600000, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, {0x0, ...})
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/internal/painter/font.go:218 +0xfd
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).RenderedTextSize(0x0?, {0xc0002de93c?, 0x7ff690e16cce?}, 0x91d7740e?, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, ...)
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/internal/driver/glfw/driver.go:72 +0x8b
fyne.io/fyne/v2.MeasureText({0xc0002de93c, 0x0}, 0x41600000, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/text.go:72 +0x98
fyne.io/fyne/v2/widget.(*RichText).updateRowBounds.func1({0xc0004ecdc0?, 0x7ff691d8cf9c?, 0xc000051c70?})
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/widget/richtext.go:481 +0x892
fyne.io/fyne/v2/widget.(*RichText).updateRowBounds(0xc000484f28)
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/widget/richtext.go:495 +0x212
fyne.io/fyne/v2/widget.(*entryRenderer).Refresh(0xc000474180)
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/widget/entry.go:1811 +0xde
fyne.io/fyne/v2/widget.(*BaseWidget).Refresh(0xc000484e08)
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/widget/widget.go:137 +0x9d
fyne.io/fyne/v2/widget.(*Entry).Refresh(0xc000484e08)
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/widget/entry.go:488 +0x52
fyne.io/fyne/v2/widget.(*DisableableWidget).Disable(0xc000484e08?)
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/widget/widget.go:207 +0x4e
fyne.io/fyne/v2/widget.(*Entry).Disable(...)
	/home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.5.3/widget/entry.go:225
main.(*serviceClient).showSettingsUI(0xc00020afc8)
	/home/runner/work/netbird/netbird/client/ui/client_ui.go:248 +0x19e
main.newServiceClient({0x7ff691da5ee1, 0x15}, {0x7ff691f536f0, 0xc0004b0280}, 0x1, 0x0)
	/home/runner/work/netbird/netbird/client/ui/client_ui.go:233 +0x215
main.main()
	/home/runner/work/netbird/netbird/client/ui/client_ui.go:92 +0x4a5
```

**Comment by moqiu365** [comment]
The latest v0.39.1 has fixed the issue of being unable to open advanced settings

**Comment by nazarewk** [comment]
same as https://github.com/netbirdio/netbird/issues/2945
