### ISSUE TITLE
http2: panic serving x.x.x.x: unable to find appropriate key

### ISSUE THREAD

**Issue by mlsmaycon** [netbirdio/netbird#427]
When using a valid URL but with an invalid response for AuthKeysLocation, management returns the error:

```shell
2022/08/17 16:19:38 http2: panic serving X.X.X.X:24409: unable to find appropriate key
goroutine 49 [running]:
net/http.(*http2serverConn).runHandler.func1()
        /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/h2_bundle.go:5896 +0x125
panic({0xa48aa0, 0xc0003e8890})
        /opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x207
github.com/netbirdio/netbird/management/server/http/middleware.NewJwtMiddleware.func1(0xc0002e8050)
        /home/runner/work/netbird/netbird/management/server/http/middleware/handler.go:48 +0x385```

**Comment by nazarewk** [comment]
@mlsmaycon is it still relevant?
