### ISSUE TITLE
HA Routing, both endpoints running in docker

### ISSUE THREAD

**Issue by itsalljustdata** [netbirdio/netbird#454]
I've got routing working across networks splendidly (awesome work guys!)

For entertainment, i thought i'd create a second Routing peer on my "Home" network to give me HA. Both of these peers are running in docker containers

The second of the containers to start up is panicking...
```
netbird  | panic: runtime error: invalid memory address or nil pointer dereference
netbird  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa84513]
netbird  | 
netbird  | goroutine 158 [running]:
netbird  | github.com/netbirdio/netbird/client/internal/routemanager.(*clientNetwork).recalculateRouteAndUpdatePeerAndSystem(0xc000540b80)
netbird  |      /home/runner/work/netbird/netbird/client/internal/routemanager/client.go:210 +0x433
netbird  | github.com/netbirdio/netbird/client/internal/routemanager.(*clientNetwork).peersStateAndUpdateWatcher(0xc000540b80)
netbird  |      /home/runner/work/netbird/netbird/client/internal/routemanager/client.go:261 +0x1ca
netbird  | created by github.com/netbirdio/netbird/client/internal/routemanager.(*DefaultManager).updateClientNetworks
netbird  |      /home/runner/work/netbird/netbird/client/internal/routemanager/manager.go:75 +0x345
netbird exited with code 2
```

**Comment by mlsmaycon** [comment]
Hello @itsalljustdata can you share your, network route and ACL configuration for both peers?

**Comment by mlsmaycon** [comment]
Turns out that there was a bug on the client that only happened when two peers are connected via ACL and the route already exist in one of them
