### ISSUE TITLE
Android App Crashes on Samsung devices

### ISSUE THREAD

**Issue by Nyeksenn** [netbirdio/netbird#979]
**Describe the problem**
Since the upgrade of the Android app to version 0.0.12
it crashes on my Galaxy S21 and Galaxy Tab S7.
The Android version of both devices is 13.

**To Reproduce**
1. Install Netbird app
2. Login to your account
3. App tries to connect and crashes

**Expected behavior**
The app should successfully establish a connection.

**Comment by SISheogorath** [comment]
Same behaviour on my device, running LineageOS or currently DivestOS. I thought it was an issue with the OS and therefore didn't want to bother, but now it sounds like it might be a more general issue.

If there is any way I can contribute debug logs, feel free to provide instructions.

**Comment by SISheogorath** [comment]
Well, I decided to dig a bit with logcat and here is what I got:

```
06-23 03:10:59.030  8976  9016 I SyncthingNativeCode: [SUFBM] INFO: Joined relay relay://85.195.207.32:22067
06-23 03:10:59.032 13017 13017 D NetbirdLib: PEERS: 0
06-23 03:10:59.033 13017 13077 I ReactNativeJS: 'onAddressChanged', { ip: '100.64.0.13/24',
06-23 03:10:59.033 13017 13077 I ReactNativeJS:   domainName: 'phone.netbird.cloud' }
06-23 03:10:59.035 13017     0 E Go      : panic: sync: negative WaitGroup counter
06-23 03:10:59.035 13017     0 E Go      : 
06-23 03:10:59.035 13017     0 E Go      : goroutine 149 [running]:
06-23 03:10:59.035 13017     0 E Go      : sync.(*WaitGroup).Add(0x20?, 0x6a44613058?)
06-23 03:10:59.035 13017     0 E Go      : 	/usr/local/go/src/sync/waitgroup.go:62 +0x10c
06-23 03:10:59.035 13017     0 E Go      : sync.(*WaitGroup).Done(...)
06-23 03:10:59.035 13017     0 E Go      : 	/usr/local/go/src/sync/waitgroup.go:87
06-23 03:10:59.036 13017     0 E Go      : github.com/netbirdio/netbird/client/internal/dns.(*DefaultServer).applyConfiguration(0x6a441407e0, {0x0, {0x6a71ad8188, 0x0, 0x0}, {0x6a71ad8188, 0x0, 0x0}})
06-23 03:10:59.036 13017     0 E Go      : 	/Users/maycon/projects/netbird/client/internal/dns/server.go:266 +0x7c
06-23 03:10:59.036 13017     0 E Go      : github.com/netbirdio/netbird/client/internal/dns.(*DefaultServer).UpdateDNSServer(0x6a441407e0, 0x274b, {0x0, {0x6a71ad8188, 0x0, 0x0}, {0x6a71ad8188, 0x0, 0x0}})
06-23 03:10:59.036 13017     0 E Go      : 	/Users/maycon/projects/netbird/client/internal/dns/server.go:250 +0x1d4
06-23 03:10:59.036 13017     0 E Go      : github.com/netbirdio/netbird/client/internal.(*Engine).updateNetworkMap(0x6a44320000, 0x6a4413adc0)
06-23 03:10:59.036 13017     0 E Go      : 	/Users/maycon/projects/netbird/client/internal/engine.go:647 +0x48c
06-23 03:10:59.036 13017     0 E Go      : github.com/netbirdio/netbird/client/internal.(*Engine).handleSync(0x6a44320000, 0x6a443c47e0)
06-23 03:10:59.036 13017     0 E Go      : 	/Users/maycon/projects/netbird/client/internal/engine.go:437 +0x1f0
06-23 03:10:59.036 13017     0 E Go      : github.com/netbirdio/netbird/client/internal.(*Engine).receiveManagementEvents.func1.1(0xe0b462f1128f62f1?)
06-23 03:10:59.036 13017     0 E Go      : 	/Users/maycon/projects/netbird/client/internal/engine.go:527 +0x28
06-23 03:10:59.036 13017     0 E Go      : github.com/netbirdio/netbird/management/client.(*GrpcClient).receiveEvents(0x6a440c8310, {0x6a70ef7d40, 0x6a44464450}, {0xf1, 0x62, 0x8f, 0x12, 0xf1, 0x62, 0xb4, ...}, ...)
06-23 03:10:59.036 13017     0 E Go      : 	/Users/maycon/projects/netbird/management/client/grpc.go:257 +0x144
06-23 03:10:59.036 13017     0 E Go      : github.com/netbirdio/netbird/management/client.(*GrpcClient).Sync.func1()
06-23 03:10:59.036 13017     0 E Go      : 	/Users/maycon/projects/netbird/management/client/grpc.go:146 +0x338
06-23 03:10:59.036 13017     0 E Go      : github.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0x6a441ebf40, {0x6c1eb600d8, 0x6a44620a20}, 0x0, {0x0?, 0x0?})
06-23 03:10:59.036 13017     0 E Go      : 	/Users/maycon/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.3/retry.go:55 +0xc8
06-23 03:10:59.036 13017     0 E Go      : github.com/cenkalti/backoff/v4.RetryNotify(...)
06-23 03:10:59.036 13017     0 E Go      : 	/Users/maycon/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.3/retry.go:34
06-23 03:10:59.036 13017     0 E Go      : github.com/cenkalti/backoff/v4.Retry(...)
06-23 03:10:59.036 13017     0 E Go      : 	/Users/maycon/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.3/retry.go:28
06-23 03:10:59.036 13017     0 E Go      : github.com/netbirdio/netbird/management/client.(*GrpcClient).Sync(0x6a440c8310, 0x6a446353e0)
06-23 03:10:59.036 13017     0 E Go      : 	/Users/maycon/projects/netbird/management/client/grpc.go:166 +0x180
06-23 03:10:59.036 13017     0 E Go      : github.com/netbirdio/netbird/client/internal.(*Engine).receiveManagementEvents.func1()
06-23 03:10:59.036 13017     0 E Go      : 	/Users/maycon/projects/netbird/client/internal/engine.go:526 +0x7c
06-23 03:10:59.036 13017     0 E Go      : created by github.com/netbirdio/netbird/client/internal.(*Engine).receiveManagementEvents
06-23 03:10:59.036 13017     0 E Go      : 	/Users/maycon/projects/netbird/client/internal/engine.go:525 +0x60
06-23 03:10:59.037 13017 13092 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 13092 (Thread-8), pid 13017 (.netbird.client)
```

**Comment by SISheogorath** [comment]
Origin of the problem was apparently setting "All" in the "Disable DNS management for these groups" setting.

Steps to reproduce:

1. Disconnect the Android client
2. Set disable DNS management for the Android peer using a group containing it
3. Try to connect the Android client

**Comment by mlsmaycon** [comment]
Hello @SISheogorath @Nyeksenn, Thanks for reporting and troubleshooting the issue. We submitted a new version with the fix to Google Play. 

I will update you when it will be published.

**Comment by mlsmaycon** [comment]
@SISheogorath @Nyeksenn, the update is live; let us know if you still have issues with the v0.0.13.

**Comment by SISheogorath** [comment]
Already tested, worked now for me. Not sure if @Nyeksenn had the same issue, so I would leave it open.

**Comment by Nyeksenn** [comment]
I also updated a minute ago and can also confirm that it fixes the problems. Thanks for the quick fix.
